"""Recover Signal.created_at for rows written before that column existed.

``Signal.trace_id``, where present, is generated by
``llm_traces.new_run_id()`` as ``"<YYYYMMDDTHHMMSS>-<8 hex chars>"`` — the UTC
instant the analysis started. That instant is already sitting in the
database as a string; recovering it needs no file I/O and does not depend on
the trace file itself still existing on disk.

Rows with no ``trace_id`` (``LLM_TRACE_DIR`` was unset when the analysis
ran) are left NULL. There is nothing to recover them from, and guessing
would put a time in the record nobody actually observed — the same reason
``evaluated_at``/``trigger`` stay NULL on rows that predate them rather than
being backfilled with an invented value.

    python -m backend.scripts.backfill_signal_timestamps [--dry-run]
"""
import argparse
import datetime

from backend.database import db


def timestamp_from_trace_id(trace_id: str) -> datetime.datetime | None:
    """The UTC instant encoded in a trace_id, or None if it doesn't parse —
    defensive against a trace_id that was ever produced a different way."""
    stamp = trace_id.split("-", 1)[0]
    try:
        return datetime.datetime.strptime(stamp, "%Y%m%dT%H%M%S")
    except ValueError:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="report what would change; write nothing"
    )
    args = parser.parse_args()

    candidates = db.get_signals_missing_created_at()
    if not candidates:
        print("Nothing to backfill — every signal already has a created_at.")
        return 0

    recovered = 0
    unrecoverable = 0
    for signal in candidates:
        trace_id = signal.trace_id
        timestamp = timestamp_from_trace_id(trace_id) if trace_id else None
        if timestamp is None:
            unrecoverable += 1
            reason = "no trace_id" if not trace_id else f"unreadable trace_id {trace_id!r}"
            print(f"  {signal.ticker} #{signal.id} ({signal.signal_date}): left NULL — {reason}")
            continue
        recovered += 1
        print(f"  {signal.ticker} #{signal.id} ({signal.signal_date}): {timestamp.isoformat()}")
        if not args.dry_run:
            db.set_signal_created_at(signal.id, timestamp)

    print()
    print(f"{recovered} recovered, {unrecoverable} left NULL (no usable trace_id).")
    if args.dry_run:
        print("Dry run — nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
